### ISSUE TITLE
Translate speech in various languages ​​into English

### ISSUE THREAD

**Issue by tismega** [I5UCC/VRCTextboxSTT#1]
Is this feature possible if you have spare time?Thank you so much for considering this request.

**Comment by I5UCC** [comment]
As Whisper does support translating into english natively this will be easy to implement, will be included in next release.

**Comment by tismega** [comment]
> As Whisper does support translating into english natively this will be easy to implement, will be included in next release.

Thank you!

**Comment by I5UCC** [comment]
Implemented in [v0.8](https://github.com/I5UCC/VRCTextboxSTT/releases/tag/v0.8)
