### ISSUE TITLE
Is it possible to load the .bin model trained by others on Hugging Face?

### ISSUE THREAD

**Issue by tismega** [I5UCC/VRCTextboxSTT#2]
For multilingual models, Fine-Tune Whisper seems to have improved recognition of specific languages. Is it possible to load models on [Hugging Face](https://huggingface.co/spaces/autoevaluate/leaderboards?dataset=mozilla-foundation%2Fcommon_voice_11_0&only_verified=0&task=automatic-speech-recognition&config=ja&split=test&metric=wer)?

**Comment by I5UCC** [comment]
Generally it should be possible, though I am currently not aware of how to load those custom models. I'll have to read a bit more into it and see if i can implement it.

**Comment by tismega** [comment]
> Generally it should be possible, though I am currently not aware of how to load those custom models. I'll have to read a bit more into it and see if i can implement it.

Thanks for your response and willingness to look into it further.

**Comment by I5UCC** [comment]
Implemented in [v1.1.0](https://github.com/I5UCC/VRCTextboxSTT/releases/tag/v1.1.0)
Tested with [noflm/whisper-base-ja-cv11](https://huggingface.co/noflm/whisper-base-ja-cv11) and [steja/whisper-small-german](https://huggingface.co/steja/whisper-small-german). 
Currently those models do not support translating into english. Until I implement some kind of translation models.
