### ISSUE TITLE
SteamVR overlay

### ISSUE THREAD

**Issue by ChxGuillaume** [I5UCC/VRCTextboxSTT#4]
Would be good to add a timeout for the text in steamvr's overlay so it doesn't stay there forever

**Comment by I5UCC** [comment]
Somewhat implemented in [v1.2.0](https://github.com/I5UCC/VRCTextboxSTT/releases/tag/v1.2.0). 
Text timeout in gerneral(Textbox, KAT and also Overlay) is now handled by TextboxSTT. Default timeout is 30 seconds. You can change the timeout in the settings.
