### ISSUE TITLE
OBS Browser Source seems to do absolutely nothing

### ISSUE THREAD

**Issue by Mage-Enderman** [I5UCC/VRCTextboxSTT#5]
I've added the HTML file to a Browser source in OBS
I've added http://localhost:5000 as a URL too
Neither seem to show any text when I type in to the TextboxSTT app
and similarly also show nothing when I use the Speech to Text function
Idk what I'm doing wrong as there's no documentation on the OBS Source option

**Comment by I5UCC** [comment]
Issue was discussed on the Support discord.
Fix was using http://127.0.0.1:5000/ instead of http://localhost:5000, because of a CORS error.
